-- Cygnus feasibility-spike schema.
--
-- Deliberately narrower than the eventual production schema: it carries only the
-- columns the Phase 0 gate exercises. The index strategy, however, is the real one,
-- because validating it is the entire point of the spike.
--
-- Idempotent so it can be applied repeatedly during development.

-- CREATE TYPE has no IF NOT EXISTS, so guard it.
DO $$
BEGIN
    CREATE TYPE cygnus_job_state AS ENUM (
        'available',  -- ready to be worked
        'scheduled',  -- scheduled_at is in the future
        'pending',    -- blocked on workflow dependencies
        'running',    -- leased by a worker
        'retryable',  -- errored, will be rescheduled
        'cancelled',  -- terminal, cancelled by the user
        'discarded',  -- terminal, retries exhausted
        'completed'   -- terminal, succeeded
    );
EXCEPTION
    WHEN duplicate_object THEN NULL;
END
$$;

CREATE TABLE IF NOT EXISTS cygnus_job (
    id               bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    state            cygnus_job_state NOT NULL DEFAULT 'available',
    kind             text        NOT NULL,
    queue            text        NOT NULL DEFAULT 'default',

    -- Lower sorts first, so 1 is the highest priority.
    priority         smallint    NOT NULL DEFAULT 1,

    args             jsonb       NOT NULL DEFAULT '{}',
    attempt          smallint    NOT NULL DEFAULT 0,
    max_attempts     smallint    NOT NULL DEFAULT 25,
    attempted_by     text[]      NOT NULL DEFAULT '{}',

    -- Every timestamp is generated by the database via now(), never by a client.
    -- Client clocks drift, and the resulting bugs are miserable to diagnose.
    created_at       timestamptz NOT NULL DEFAULT now(),
    scheduled_at     timestamptz NOT NULL DEFAULT now(),
    attempted_at     timestamptz,
    lease_expires_at timestamptz,
    finalized_at     timestamptz,

    CONSTRAINT cygnus_job_priority_range CHECK (priority BETWEEN 1 AND 4),
    CONSTRAINT cygnus_job_max_attempts_positive CHECK (max_attempts > 0)
);

-- The hot path.
--
-- Partial on state = 'available', so the index holds only genuinely workable rows and
-- stays small even when the table holds a hundred million historical jobs. The column
-- order must match the fetch query's ORDER BY exactly, or PostgreSQL adds a sort node
-- and throughput collapses at depth. `spike explain` asserts this.
CREATE INDEX IF NOT EXISTS cygnus_job_fetch_idx
    ON cygnus_job (queue, priority, scheduled_at, id)
    WHERE state = 'available';

-- Scheduler sweep: promotes due jobs to 'available'.
CREATE INDEX IF NOT EXISTS cygnus_job_schedule_idx
    ON cygnus_job (scheduled_at, id)
    WHERE state IN ('scheduled', 'retryable');

-- Rescuer sweep: finds jobs whose worker died and whose lease has lapsed.
CREATE INDEX IF NOT EXISTS cygnus_job_lease_idx
    ON cygnus_job (lease_expires_at)
    WHERE state = 'running';
